# Generated by Django 3.2.8 on 2021-11-04 19:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel_agent', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tagent',
            new_name='agent',
        ),
    ]
