# Generated by Django 3.2.8 on 2021-11-06 21:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel_agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='booked_by',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
