# Generated by Django 3.2.8 on 2021-11-06 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agent', '0002_rename_tagent_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_logo', models.ImageField(upload_to='company/logo')),
                ('primary_background', models.ImageField(blank=True, null=True, upload_to='company/background')),
                ('short_description', models.TextField(max_length=200, null=True)),
                ('company_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_root', to='travel_agent.agent')),
            ],
        ),
    ]
