# Generated by Django 3.2.8 on 2021-11-06 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agent', '0003_companyinfo_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='title',
        ),
    ]
