# Generated by Django 3.2.8 on 2021-11-06 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agent', '0003_companyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='company/post_image')),
                ('location', models.CharField(choices=[('Chattogram', 'Chattogram'), ('Rajshahi', 'Rajshahi'), ('Khulna', 'Khulna'), ('Barishal', 'Barishal'), ('Sylhet', 'Sylhet'), ('Dhaka', 'Dhaka'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh')], max_length=15, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_agent.agent')),
            ],
        ),
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotel/room')),
                ('type', models.CharField(choices=[('single', 'Single'), ('double', 'Double')], max_length=15, null=True)),
                ('facilities', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_agent.hotels')),
            ],
        ),
    ]
