# Generated by Django 3.2.8 on 2021-11-06 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agent', '0004_hotels_rooms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hotels',
            new_name='hotel',
        ),
        migrations.RenameModel(
            old_name='rooms',
            new_name='room',
        ),
    ]
