# Generated by Django 3.2.8 on 2021-11-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agent', '0004_remove_room_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
