# Generated by Django 3.2.8 on 2021-11-06 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agent', '0006_alter_room_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='hotel',
            new_name='rel_hotel',
        ),
    ]
