# Generated by Django 3.2.8 on 2021-11-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agent', '0008_alter_room_rel_hotel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hotel',
            new_name='companyHotel',
        ),
    ]
