# Generated by Django 3.2.8 on 2021-11-07 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agent', '0009_rename_hotel_companyhotel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='room',
        ),
    ]
