# Generated by Django 3.2.8 on 2021-11-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agent', '0011_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='rel_hotel',
        ),
        migrations.AddField(
            model_name='room',
            name='rel_hotel',
            field=models.ManyToManyField(related_name='root_hotels', to='travel_agent.companyHotel'),
        ),
    ]
