# Generated by Django 3.2.8 on 2021-11-07 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agent', '0013_auto_20211108_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_hotels', to='travel_agent.hotel'),
        ),
    ]
