# Generated by Django 3.2.8 on 2021-11-06 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('features', '0002_alter_packagetour_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagetour',
            name='entry',
        ),
        migrations.AddField(
            model_name='packagetour',
            name='entry',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
